services:
  backend:
    image: org-company-management-backend
    container_name: backend
    build:
      context: ./BackEnd
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  frontend:
    image: org-company-management-frontend
    container_name: frontend
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
